### ISSUE TITLE
post-process Kuromoji output

### ISSUE THREAD

**Issue by verenablaschke** [ismla-japanese-helper/japanese-helper#25]
- inflected verb forms are analyzed as sequences of tokens (e.g. ```ありません``` -> ```あり   ませ   ん```)
- compound nouns are analyzed as sequences of tokens (eg. ```計算言語学``` (computational linguistics; this is actually an entry in our Wiktionary file!) -> ```計算   言語   学```)

I quickly compared the ```ipadic, jumandic, unidic``` and ```naist-jdic``` versions of Kuromoji, but they all appear to work the same in such cases.

**Comment by x-ji** [comment]
The case of inflection is dealt with in e9a4df44903e4e88662553c8d222dd4bff0a2831

Compound nouns are harder since they are essentially out of vocabulary for the dictionary that Kuromoji uses? They don't have any special indicators in Kuromoji such as one returned by `getConjugationForm()`. One way could be to search through all possible combinations in the sentence and see if any combination is actually found in Wiktionary, and display them in an additional table below. However that would be resource-intensive.

**Comment by x-ji** [comment]
We can check all combinations of nouns and see if any combination matches

**Comment by verenablaschke** [comment]
implemented in the above-mentioned commit; otherwise addressed in the report
