### ISSUE TITLE
difficulty rating for tokens

### ISSUE THREAD

**Issue by verenablaschke** [ismla-japanese-helper/japanese-helper#26]
from the project proposal:
> If time permits, we could implement functionalities that provide further information to the user, such as the full inflection table and the difficulty rating of the word.

**Comment by verenablaschke** [comment]
If querying Jisho for Wanikani levels (http://jisho.org/api/v1/search/words?keyword=有る) is too complicated with GWT, we could make use of [this table about han characters in Unicode](https://www.unicode.org/versions/Unicode10.0.0/ch18.pdf#page=6) to classify kanji as either "common" or "rare" via ```Character.UnicodeBlock.of(char c)```. (How helpful this actually is remains undecided, but we'd at least honour that part of the project proposal.)


As for getting information from Jisho, I found [this GWT tutorial](http://www.gwtproject.org/doc/latest/tutorial/JSON.html) for retrieving JSON data; maybe that might be helpful.

**Comment by x-ji** [comment]
My concern is that if we query jisho for each token we get, it might take a very long time for all the queries to finish, since they will all be treated as independent from each other. Also, to run a query just to extract a difficulty rating in the end seems a bit extraneous.

We can explain in the final report that Jisho's API is still basic and doesn't allow querying a whole sentence, making such usage difficult.

Good find about the Unicode table. That's an interesting read! We might use that information. Also, there's apparently an official list of 2136 common kanji at https://en.wikipedia.org/wiki/J%C5%8Dy%C5%8D_kanji. Maybe we can use that information as well.

**Comment by verenablaschke** [comment]
That's a good point! I also tried out getting the information via GWT ```Request```, but I ran into [essentially this problem](https://stackoverflow.com/questions/20881532/no-access-control-allow-origin-header-is-present-on-the-requested-resource), but didn't find an easy approach to solving this with GWT & Java.

I really like the idea about using that jouyou kanji list! We could even use [this Wiki page](https://en.wikipedia.org/wiki/Kyōiku_kanji) that lists a subgroup of jouyou kanji by when they are taught in Japanese schools. Processing either the HTML source(s) of the Wiki page(s) or the Wikipedia-internal markup should be simple enough.

**Comment by x-ji** [comment]
Sure. Let me do it then. Thanks for all the work on the report. It already looks relatively complete! I will also add a section in the report about difficulty ratings.

I think we can add a subsection under "Discussion" to compare the original proposal with the final outcome.

**Comment by x-ji** [comment]
4e71560cfe3a51b73da1b62b9cb965924915f393
