### ISSUE TITLE
Deal with the entries that also contain parenthesis, i.e. with an alternative/optional spelling. Maybe also add additional entries in the dictionary to handle it

### ISSUE THREAD

**Issue by x-ji** [ismla-japanese-helper/japanese-helper#8]

**Comment by x-ji** [comment]
There is currently already some code that directly substitutes the parenthesis. Should we just go with that?

**Comment by verenablaschke** [comment]
That's more of a special case since I need the final な to properly apply the inflection template. (Although I should additionally add the version without -な to the tokens collection; good point.)

I was thinking more of something like [this part in the ```inflect``` method](https://github.com/ismla-japanese-helper/japanese-helper/blob/74420fd96db114859c2ed1353e2b07c651c23f80/src/main/java/de/ws1718/ismla/JapaneseHelper/preprocessing/WiktionaryPreprocessor.java#L156), where we add one token that contains the optional content and one token that does not.

**Comment by verenablaschke** [comment]
In the new Wiktionary dump, this is only the case for ```A[na]``` adjectives (#9) and inflection templates. Both cases are already dealt with, so we can just close this issue.
